### ISSUE TITLE
Feature Request Xiaosheng #2

### ISSUE THREAD

**Issue by brands-d** [brands-d/kMap#11]
use \u212B for Ångstrom instead of just "A"

**Comment by brands-d** [comment]
Addressed on 03.10.2020 in the commit fb452b1. Waiting for confirmation.

**Comment by tromask** [comment]
I suspect that the label "1/A" in slicedata.py should be changed too, to display local sliced data in 1/Å.

**Comment by brands-d** [comment]
You are absolutely right, I fixed that in commit e1d23ec.

**Comment by tromask** [comment]
Thx! https://github.com/brands-d/kMap/commit/ce8ee502fb5105f24ec2402463b32d25a67279c2 does fix File-Load Sliced Data-From Orbitals (or From hnu-dependence), but does not fix File-Load Sliced Data-Locally. Somewhere else may need to be changed.

**Comment by brands-d** [comment]
Local .hf5 files should contain information about the axes like the units (see https://github.com/brands-d/kMap/blob/master/docs/Sliced%20Data%20Description.txt) so the data you load needs to use the correct unit symbol. I don't change that inside kMap.py and the structure of sliced data as a general 3D data with three potentially different axes makes it illogical to do so.

**Comment by brands-d** [comment]
The files were updated in branch "peter" and now the correct symbol gets displayed.
